<script lang="ts">
 import {onMount} from 'svelte'; import {api} from '../lib/api'; import {duration,lastPlayed,imageSrc} from '../lib/time'; import type {GameSummary,SortKey} from '../lib/types';
 export let refresh=0; export let openGame:(id:number)=>void; let games:GameSummary[]=[],search='',brand='',sort:SortKey='last_played',descending=true,error=''; let loadedKey='';
 async function load(){try{games=await api.listGames(search,brand,sort,descending)}catch(e){error=String(e)}}
 $: {const key=`${refresh}|${search}|${brand}|${sort}|${descending}`;if(key!==loadedKey){loadedKey=key;load();}}
 let brands:string[]=[]; onMount(()=>{api.listBrands().then(value=>brands=value).catch(e=>error=String(e));const timer=setInterval(load,1000);return()=>clearInterval(timer)});
 async function launch(gameId:number){try{await api.launchGame(gameId)}catch(e){error=String(e)}}
</script>
<section class="toolbar"><label class="search-control"><span>タイトル検索</span><input placeholder="ゲームタイトルを入力" bind:value={search}/></label><label><span>ブランド</span><select bind:value={brand}><option value="">すべてのブランド</option>{#each brands as b}<option>{b}</option>{/each}</select></label><label><span>並び順</span><select bind:value={sort}><option value="last_played">最終プレイ</option><option value="total_playtime">プレイ時間</option><option value="title">タイトル</option><option value="brand">ブランド</option><option value="release_date">発売日</option><option value="created_at">登録日</option><option value="session_count">セッション数</option></select></label><button onclick={()=>descending=!descending}>{descending?'降順':'昇順'}</button></section>
{#if error}<p class="error">{error}</p>{/if}{#if !games.length}<div class="empty">ゲームがありません。「ゲーム追加」から登録してください。</div>{/if}
<div class="grid">{#each games as g}<article class="card"><button class="card-main" onclick={()=>openGame(g.id)} aria-label={`${g.title}の詳細を開く`}><div class="card-image">{#if g.thumbnail_path}<img src={imageSrc(g.thumbnail_path)} alt=""/>{:else}<div class="placeholder">NO IMAGE</div>{/if}</div><div class="card-info"><h2>{g.title}</h2><p>{g.brand??'ブランド未設定'}</p><strong>{duration(g.total_playtime_seconds)}</strong><small>最終: {lastPlayed(g.last_played)} ・ {g.session_count}回</small></div></button><button class="launch-overlay" onclick={()=>launch(g.id)} aria-label={`${g.title}を起動`}>▶ 起動</button></article>{/each}</div>
